
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


shell_command:
#  get_temperature_vichnya: /config/scripts/vishnya.sh
#  get_temperature_fomino: /config/scripts/fomino.sh
  get_boa_snapshot: /config/scripts/get_boa_snapshot.sh
